version: '3'

services:
  discovery-service:
    image: 'discovery-service:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discovery-service
    hostname: discovery-service
    ports:
      - "8761:8761"